# -*- coding: utf-8 -*-
import sqlite3
import json
import os

# Warp 数据库路径
db_path = os.path.join(os.environ['LOCALAPPDATA'], 'warp', 'Warp', 'data', 'warp.sqlite')

print(f"数据库路径: {db_path}\n")

if not os.path.exists(db_path):
    print("数据库文件不存在！")
    exit(1)

conn = sqlite3.connect(db_path)
conn.text_factory = str
cursor = conn.cursor()

print("=" * 80)
print("【1】查看所有 generic_string_objects 表中的数据")
print("=" * 80)
cursor.execute("SELECT id, data FROM generic_string_objects")
all_rows = cursor.fetchall()
print(f"表中共有 {len(all_rows)} 条记录\n")

# 分类显示
memory_rules = []
other_data = []

for row in all_rows:
    row_id, data = row
    try:
        parsed = json.loads(data)
        if 'memory' in parsed:
            memory_rules.append((row_id, data, parsed))
        else:
            other_data.append((row_id, data, parsed))
    except:
        other_data.append((row_id, data, None))

print(f"包含 'memory' 的记录: {len(memory_rules)} 条")
print(f"其他类型记录: {len(other_data)} 条\n")

# 显示 memory 规则
if memory_rules:
    print("-" * 80)
    print("【Memory 规则详情】")
    print("-" * 80)
    for row_id, raw_data, parsed_data in memory_rules:
        print(f"\nID: {row_id}")
        print(f"原始 JSON (前200字符): {raw_data[:200]}")
        print(f"完整结构:")
        print(json.dumps(parsed_data, indent=2, ensure_ascii=False))
        print(f"字段:")
        if 'memory' in parsed_data:
            mem = parsed_data['memory']
            print(f"  - name: {mem.get('name', 'N/A')}")
            print(f"  - content (前100字符): {str(mem.get('content', ''))[:100]}")
            print(f"  - is_autogenerated: {mem.get('is_autogenerated', 'N/A')}")
            # 检查是否有其他字段
            other_fields = [k for k in mem.keys() if k not in ['name', 'content', 'is_autogenerated']]
            if other_fields:
                print(f"  - 其他字段: {other_fields}")
        print("-" * 40)

# 显示其他类型的数据（看看还有什么）
if other_data:
    print("\n" + "=" * 80)
    print("【其他类型数据示例】（前3条）")
    print("=" * 80)
    for i, (row_id, raw_data, parsed_data) in enumerate(other_data[:3]):
        print(f"\nID: {row_id}")
        if parsed_data:
            print(f"JSON 结构: {json.dumps(parsed_data, indent=2, ensure_ascii=False)[:200]}")
        else:
            print(f"原始数据 (前100字符): {raw_data[:100]}")
        print("-" * 40)

# 检查是否有其他表可能存储规则
print("\n" + "=" * 80)
print("【2】检查其他可能相关的表")
print("=" * 80)

# 检查 project_rules 表
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='project_rules'")
if cursor.fetchone():
    print("\n发现 project_rules 表：")
    cursor.execute("PRAGMA table_info(project_rules)")
    print("表结构:")
    for col in cursor.fetchall():
        print(f"  - {col[1]} ({col[2]})")
    
    cursor.execute("SELECT COUNT(*) FROM project_rules")
    count = cursor.fetchone()[0]
    print(f"记录数: {count}")
    
    if count > 0:
        cursor.execute("SELECT * FROM project_rules LIMIT 3")
        print("\n前3条记录:")
        for row in cursor.fetchall():
            print(f"  {row}")

# 检查 ai_memory_panes 表
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE '%memory%' OR name LIKE '%rule%'")
related_tables = cursor.fetchall()
if related_tables:
    print("\n发现可能相关的表:")
    for table in related_tables:
        print(f"  - {table[0]}")

conn.close()

print("\n" + "=" * 80)
print("分析完成！")
print("=" * 80)

