import sqlite3
import json
import os

# Warp 数据库路径
db_path = os.path.join(os.environ['LOCALAPPDATA'], 'warp', 'Warp', 'data', 'warp.sqlite')

print(f"数据库路径: {db_path}")
print(f"数据库存在: {os.path.exists(db_path)}")
print()

if not os.path.exists(db_path):
    print("数据库文件不存在！")
    exit(1)

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# 1. 查看所有表
print("=" * 60)
print("所有表:")
print("=" * 60)
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables = cursor.fetchall()
for table in tables:
    print(f"  - {table[0]}")
print()

# 2. 查看 generic_string_objects 表结构
print("=" * 60)
print("generic_string_objects 表结构:")
print("=" * 60)
cursor.execute("PRAGMA table_info(generic_string_objects)")
columns = cursor.fetchall()
for col in columns:
    print(f"  {col[1]} ({col[2]}) - {'NOT NULL' if col[3] else 'NULL'} - DEFAULT: {col[4]}")
print()

# 3. 查看所有包含 memory 的记录
print("=" * 60)
print("所有包含 'memory' 的记录:")
print("=" * 60)
cursor.execute("SELECT id, data FROM generic_string_objects WHERE data LIKE '%memory%'")
rows = cursor.fetchall()
print(f"找到 {len(rows)} 条记录\n")

for idx, row in enumerate(rows, 1):
    rule_id = row[0]
    raw_data = row[1]
    print(f"\n【记录 {idx}】 ID: {rule_id}")
    print(f"原始数据长度: {len(raw_data)} 字符")
    print(f"原始JSON:")
    try:
        data = json.loads(raw_data)
        print(json.dumps(data, indent=2, ensure_ascii=False))
        
        if 'memory' in data:
            print(f"\n解析结果:")
            print(f"  - name: {data['memory'].get('name', 'N/A')}")
            print(f"  - content length: {len(data['memory'].get('content', ''))}")
            print(f"  - is_autogenerated: {data['memory'].get('is_autogenerated', 'N/A')}")
    except Exception as e:
        print(f"解析失败: {e}")
        print(f"原始数据: {raw_data[:200]}")
    print("-" * 60)

# 4. 统计信息
print("\n" + "=" * 60)
print("统计信息:")
print("=" * 60)
cursor.execute("SELECT COUNT(*) FROM generic_string_objects")
total = cursor.fetchone()[0]
print(f"generic_string_objects 总记录数: {total}")

cursor.execute("SELECT COUNT(*) FROM generic_string_objects WHERE data LIKE '%memory%'")
memory_count = cursor.fetchone()[0]
print(f"包含 'memory' 的记录数: {memory_count}")

cursor.execute("SELECT COUNT(*) FROM generic_string_objects WHERE data LIKE '%memory%' AND data LIKE '%content%'")
memory_content_count = cursor.fetchone()[0]
print(f"同时包含 'memory' 和 'content' 的记录数: {memory_content_count}")

conn.close()

print("\n完成！")

